"use client";

import { useLogoStore } from "@/lib/use-logo-store";
import { Button } from "@/components/ui/button";
import { X, Download, Copy } from "lucide-react";
import { useCallback, useRef } from "react";
import { getCanvasForExport } from "./logo-canvas";

export function AnalysisCard() {
  const { showAnalysis, setShowAnalysis, gridData, imageElement, settings } =
    useLogoStore();
  const cardRef = useRef<HTMLDivElement>(null);

  const handleDownload = useCallback(() => {
    if (!imageElement || !gridData) return;

    const canvas = document.createElement("canvas");
    const w = 1200;
    const h = 630;
    canvas.width = w;
    canvas.height = h;
    const ctx = canvas.getContext("2d")!;

    // Background
    ctx.fillStyle = "#0a0a0a";
    ctx.fillRect(0, 0, w, h);

    // Logo + grid preview (left side)
    const previewCanvas = getCanvasForExport(imageElement, gridData, settings, "combined", 1);
    const pAspect = previewCanvas.width / previewCanvas.height;
    const pMaxW = 500;
    const pMaxH = 500;
    let pW: number, pH: number;
    if (pAspect > pMaxW / pMaxH) {
      pW = pMaxW;
      pH = pMaxW / pAspect;
    } else {
      pH = pMaxH;
      pW = pMaxH * pAspect;
    }
    const pX = 60;
    const pY = (h - pH) / 2;
    ctx.drawImage(previewCanvas, pX, pY, pW, pH);

    // Scores (right side)
    const sx = 620;
    ctx.fillStyle = "#e5e5e5";
    ctx.font = "bold 28px sans-serif";
    ctx.fillText("Grid Analysis", sx, 100);

    ctx.font = "16px sans-serif";
    ctx.fillStyle = "#737373";
    ctx.fillText("Logo Grid Generator", sx, 130);

    const scores = [
      { label: "Golden Ratio", value: gridData.scores.goldenRatio },
      { label: "Symmetry", value: gridData.scores.symmetry },
      { label: "Grid Alignment", value: gridData.scores.gridAlignment },
    ];

    scores.forEach((s, i) => {
      const y = 200 + i * 100;

      ctx.fillStyle = "#e5e5e5";
      ctx.font = "bold 48px sans-serif";
      ctx.fillText(`${s.value}%`, sx, y);

      ctx.fillStyle = "#737373";
      ctx.font = "16px sans-serif";
      ctx.fillText(s.label, sx, y + 24);

      // Score bar
      ctx.fillStyle = "#262626";
      ctx.fillRect(sx, y + 36, 300, 4);
      const barColor = s.value >= 70 ? "#22c55e" : s.value >= 40 ? "#eab308" : "#ef4444";
      ctx.fillStyle = barColor;
      ctx.fillRect(sx, y + 36, (s.value / 100) * 300, 4);
    });

    // Overall score
    const overall = Math.round(
      (scores.reduce((a, s) => a + s.value, 0)) / scores.length
    );
    ctx.fillStyle = "#22d3ee";
    ctx.font = "bold 64px sans-serif";
    ctx.fillText(`${overall}`, sx + 350, 300);
    ctx.fillStyle = "#737373";
    ctx.font = "16px sans-serif";
    ctx.fillText("Overall", sx + 350, 330);

    // Watermark
    ctx.fillStyle = "#404040";
    ctx.font = "12px sans-serif";
    ctx.fillText("Generated by Logo Grid Generator", 60, h - 30);

    const link = document.createElement("a");
    link.download = "logo-grid-analysis.png";
    link.href = canvas.toDataURL("image/png");
    link.click();
  }, [imageElement, gridData, settings]);

  const handleCopy = useCallback(async () => {
    if (!cardRef.current) return;
    // Copy scores as text
    if (!gridData) return;
    const text = `Logo Grid Analysis\nGolden Ratio: ${gridData.scores.goldenRatio}%\nSymmetry: ${gridData.scores.symmetry}%\nGrid Alignment: ${gridData.scores.gridAlignment}%\nOverall: ${Math.round((gridData.scores.goldenRatio + gridData.scores.symmetry + gridData.scores.gridAlignment) / 3)}%`;
    await navigator.clipboard.writeText(text);
  }, [gridData]);

  if (!showAnalysis || !gridData) return null;

  const overall = Math.round(
    (gridData.scores.goldenRatio + gridData.scores.symmetry + gridData.scores.gridAlignment) / 3
  );

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm">
      <div
        ref={cardRef}
        className="bg-[#0a0a0a] border border-neutral-800 rounded-2xl p-8 max-w-lg w-full mx-4 relative"
      >
        <button
          onClick={() => setShowAnalysis(false)}
          className="absolute top-4 right-4 text-neutral-500 hover:text-neutral-300"
        >
          <X className="w-5 h-5" />
        </button>

        <h2 className="text-xl font-bold text-neutral-200 mb-1">Grid Analysis</h2>
        <p className="text-sm text-neutral-500 mb-6">
          How well your logo maps to geometric grids
        </p>

        {/* Overall score */}
        <div className="flex items-center justify-center mb-8">
          <div className="w-28 h-28 rounded-full border-4 border-cyan-500/30 flex items-center justify-center">
            <div className="text-center">
              <span className="text-4xl font-bold text-cyan-400">{overall}</span>
              <span className="text-sm text-neutral-500 block">/ 100</span>
            </div>
          </div>
        </div>

        {/* Individual scores */}
        <div className="space-y-4 mb-8">
          <ScoreRow label="Golden Ratio Adherence" value={gridData.scores.goldenRatio} />
          <ScoreRow label="Symmetry" value={gridData.scores.symmetry} />
          <ScoreRow label="Grid Alignment" value={gridData.scores.gridAlignment} />
        </div>

        {/* Actions */}
        <div className="flex gap-3">
          <Button
            onClick={handleDownload}
            className="flex-1 gap-2 bg-cyan-600 hover:bg-cyan-500 text-white"
          >
            <Download className="w-4 h-4" />
            Download Card
          </Button>
          <Button
            variant="outline"
            onClick={handleCopy}
            className="gap-2 bg-neutral-900 border-neutral-700 hover:bg-neutral-800 text-neutral-300"
          >
            <Copy className="w-4 h-4" />
            Copy
          </Button>
        </div>
      </div>
    </div>
  );
}

function ScoreRow({ label, value }: { label: string; value: number }) {
  const color =
    value >= 70 ? "bg-green-500" : value >= 40 ? "bg-yellow-500" : "bg-red-500";
  return (
    <div>
      <div className="flex justify-between mb-1">
        <span className="text-sm text-neutral-400">{label}</span>
        <span className="text-sm font-mono font-bold text-neutral-200">{value}%</span>
      </div>
      <div className="h-2 bg-neutral-800 rounded-full overflow-hidden">
        <div
          className={`h-full ${color} rounded-full transition-all duration-700`}
          style={{ width: `${value}%` }}
        />
      </div>
    </div>
  );
}
