"use client";

import { useLogoStore } from "@/lib/use-logo-store";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Download, Copy } from "lucide-react";
import { useCallback } from "react";
import { getCanvasForExport } from "./logo-canvas";

export function AnalysisDialog() {
  const { showAnalysis, setShowAnalysis, gridData, imageElement, settings } = useLogoStore();

  const handleDownload = useCallback(() => {
    if (!imageElement || !gridData) return;

    const canvas = document.createElement("canvas");
    const w = 1200;
    const h = 630;
    canvas.width = w;
    canvas.height = h;
    const ctx = canvas.getContext("2d")!;

    ctx.fillStyle = "#0a0a0a";
    ctx.fillRect(0, 0, w, h);

    const previewCanvas = getCanvasForExport(imageElement, gridData, settings, "combined", 1);
    const pAspect = previewCanvas.width / previewCanvas.height;
    const pMaxW = 500;
    const pMaxH = 500;
    let pW: number, pH: number;
    if (pAspect > pMaxW / pMaxH) { pW = pMaxW; pH = pMaxW / pAspect; }
    else { pH = pMaxH; pW = pMaxH * pAspect; }
    const pX = 60;
    const pY = (h - pH) / 2;
    ctx.drawImage(previewCanvas, pX, pY, pW, pH);

    const sx = 620;
    ctx.fillStyle = "#e5e5e5";
    ctx.font = "bold 28px sans-serif";
    ctx.fillText("Grid Analysis", sx, 100);
    ctx.font = "16px sans-serif";
    ctx.fillStyle = "#a3a3a3";
    ctx.fillText("Logo Grid Generator", sx, 130);

    const scores = [
      { label: "Golden Ratio", value: gridData.scores.goldenRatio },
      { label: "Symmetry", value: gridData.scores.symmetry },
      { label: "Grid Alignment", value: gridData.scores.gridAlignment },
    ];

    scores.forEach((s, i) => {
      const y = 200 + i * 100;
      ctx.fillStyle = "#e5e5e5";
      ctx.font = "bold 48px sans-serif";
      ctx.fillText(`${s.value}%`, sx, y);
      ctx.fillStyle = "#a3a3a3";
      ctx.font = "16px sans-serif";
      ctx.fillText(s.label, sx, y + 24);

      ctx.fillStyle = "#262626";
      ctx.fillRect(sx, y + 36, 300, 4);
      const barColor = s.value >= 70 ? "#22c55e" : s.value >= 40 ? "#eab308" : "#ef4444";
      ctx.fillStyle = barColor;
      ctx.fillRect(sx, y + 36, (s.value / 100) * 300, 4);
    });

    const overall = Math.round(scores.reduce((a, s) => a + s.value, 0) / scores.length);
    ctx.fillStyle = "#22d3ee";
    ctx.font = "bold 64px sans-serif";
    ctx.fillText(`${overall}`, sx + 350, 300);
    ctx.fillStyle = "#a3a3a3";
    ctx.font = "16px sans-serif";
    ctx.fillText("Overall", sx + 350, 330);

    ctx.fillStyle = "#737373";
    ctx.font = "12px sans-serif";
    ctx.fillText("Generated by Logo Grid Generator", 60, h - 30);

    const link = document.createElement("a");
    link.download = "logo-grid-analysis.png";
    link.href = canvas.toDataURL("image/png");
    link.click();
  }, [imageElement, gridData, settings]);

  const handleCopy = useCallback(async () => {
    if (!gridData) return;
    const overall = Math.round(
      (gridData.scores.goldenRatio + gridData.scores.symmetry + gridData.scores.gridAlignment) / 3
    );
    const text = `Logo Grid Analysis\nGolden Ratio: ${gridData.scores.goldenRatio}%\nSymmetry: ${gridData.scores.symmetry}%\nGrid Alignment: ${gridData.scores.gridAlignment}%\nOverall: ${overall}%`;
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // ignore
    }
  }, [gridData]);

  if (!gridData) return null;

  const overall = Math.round(
    (gridData.scores.goldenRatio + gridData.scores.symmetry + gridData.scores.gridAlignment) / 3
  );

  return (
    <Dialog open={showAnalysis} onOpenChange={setShowAnalysis}>
      <DialogContent className="bg-[#0a0a0a] border border-neutral-800 text-neutral-200 sm:max-w-md p-6">
        <DialogHeader>
          <DialogTitle className="text-lg text-neutral-50">Grid Analysis</DialogTitle>
          <DialogDescription className="text-sm text-neutral-300">
            How well your logo maps to geometric grids.
          </DialogDescription>
        </DialogHeader>

        {/* Overall score ring */}
        <div className="flex items-center justify-center py-2">
          <div className="w-28 h-28 rounded-full border-4 border-cyan-500/30 flex items-center justify-center">
            <div className="text-center">
              <span className="text-4xl font-bold text-cyan-300">{overall}</span>
              <span className="text-sm text-neutral-400 block">/ 100</span>
            </div>
          </div>
        </div>

        {/* Individual scores */}
        <div className="space-y-4">
          <ScoreRow
            label="Golden Ratio Adherence"
            value={gridData.scores.goldenRatio}
            explanation="How closely the detected circle radii match Fibonacci sequence proportions (1, 1, 2, 3, 5, 8, 13...)."
          />
          <ScoreRow
            label="Symmetry"
            value={gridData.scores.symmetry}
            explanation="How mirror-balanced the logo is along its vertical center axis."
          />
          <ScoreRow
            label="Grid Alignment"
            value={gridData.scores.gridAlignment}
            explanation="What percentage of the logo's edges fall on the detected construction circles."
          />
        </div>

        {/* Summary */}
        <Card className="p-3 bg-neutral-900 border-neutral-800">
          <p className="text-xs text-neutral-200 leading-relaxed">
            {overall >= 80
              ? "Your logo has strong geometric foundations — curves follow mathematical proportions that create natural visual harmony."
              : overall >= 50
              ? "Your logo has some geometric structure. Using the Tweaked tab can strengthen mathematical precision."
              : "Your logo is more organic than geometric. Try the Tweaked tab to snap curves onto ideal grid circles."}
          </p>
        </Card>

        {/* Actions */}
        <div className="flex gap-2 pt-2">
          <Button
            onClick={handleDownload}
            className="flex-1 bg-cyan-500 hover:bg-cyan-400 text-neutral-950 font-semibold"
          >
            <Download className="w-4 h-4 mr-2" />
            Download Card
          </Button>
          <Button
            variant="outline"
            onClick={handleCopy}
            className="bg-neutral-900 border-neutral-700 hover:bg-neutral-800 text-neutral-200"
          >
            <Copy className="w-4 h-4 mr-2" />
            Copy
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function ScoreRow({
  label, value, explanation,
}: {
  label: string; value: number; explanation: string;
}) {
  const rating = value >= 80 ? "Excellent" : value >= 60 ? "Good" : value >= 40 ? "Fair" : "Low";
  const ratingColor =
    value >= 70
      ? "bg-green-500/15 text-green-300"
      : value >= 40
      ? "bg-yellow-500/15 text-yellow-300"
      : "bg-red-500/15 text-red-300";

  return (
    <div>
      <div className="flex justify-between items-center mb-1.5">
        <span className="text-sm text-neutral-200">{label}</span>
        <div className="flex items-center gap-2">
          <Badge variant="secondary" className={`text-xs border-0 ${ratingColor}`}>
            {rating}
          </Badge>
          <span className="text-sm font-mono font-semibold text-neutral-100">{value}%</span>
        </div>
      </div>
      <Progress value={value} aria-label={label} />
      <p className="text-xs text-neutral-300 mt-1.5 leading-relaxed">{explanation}</p>
    </div>
  );
}
